name: cargo audit
on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *'

permissions:
  contents: read
  issues: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rustsec/audit-check@bump-node16
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

